Repository oss2025hnu/reposcore-js, pull requests merged in 2025-05, with the labels that each got.

#359 [DOC] README.md 내 중복 CLI 옵션 표기 수정
  index.js
Labels: documentation

#393 [STYLE] 들여쓰기 오타 수정
  lib/Util.js
Labels: typo

#397 README.md 오타 수정
  README.md
Labels: typo

#422 HTML 미리보기를 위한 Live Server 확장 기능 devcontainer에 추가
  .devcontainer/devcontainer.json
Labels: enhancement

#435 Cherry pick 문서 readme에 링크
  README.md
  Readme_Template.md
Labels: documentation

#457 docs/img 내부 파일명 변경/폴더추가
  docs/fork_sync_guide.md
  docs/img/fork_sync_guide/fork_sync_button.png
  docs/img/token_guide/token_step1_profile.jpg
  docs/img/token_guide/token_step2_setting.jpg
  docs/img/token_guide/token_step3_Developer.jpg
  docs/img/token_guide/token_step4_fine_grained.jpg
  docs/img/token_guide/token_step5_token_create.jpg
  docs/img/token_guide/token_step6_token_access.jpg
  docs/token_guide.md
Labels: documentation

#459 [BUG] 인코딩 언어 지정
  lib/htmlGenerator.js
Labels: bug

#462 [FEAT] calculateAverageScore 빈 배열 예외 처리 PR
  lib/analyzer.js
Labels: enhancement

#496 cherry-pick_guide.md 파일 양식 수정
  docs/cherry-pick_guide.md
Labels: documentation

#504 readme에 github api 가이드 문서 링크 추가
  README.md
  Readme_Template.md
Labels: documentation
