Repository oss2025hnu/reposcore-js, pull requests merged in 2025-04, with the labels that each got.

#7 collectIssues 함수 수정 요청에 대한 PR
  index.js
  lib/analyzer.js
Labels: enhancement

#10 [DOC] 점수 산출 공식 추가
  README.md
Labels: documentation

#11 [FEAT] 선택적 인증 기능 구현 요청에 대한 PR
  README.md
  index.js
  lib/analyzer.js
  package-lock.json
Labels: enhancement

#19 analyzer.js 내 코드 오타 수정
  lib/analyzer.js
Labels: documentation

#25 [FEAT] calculateScores 함수 구현
  lib/analyzer.js
Labels: enhancement

#51 [FEAT] 차트를 이미지로 저장 PR 요청
  lib/analyzer.js
  package-lock.json
  package.json
Labels: enhancement

#66 [DOC] gitignore 파일에 score_table.txt 추가
  .gitignore
Labels: documentation

#85 [BUG] 점수가 0점으로 계산되는 버그 수정 PR
  lib/analyzer.js
Labels: enhancement

#88 index.js에서 --format 옵션 값 유효성 검사 PR
  README.md
  index.js
Labels: enhancement

#93 [FEAT] 중복된 코드 제거 요청에 대한 PR
  lib/analyzer.js
Labels: enhancement

#119 [REFACTOR] 사용하지 않는 property 삭제
  lib/analyzer.js
Labels: enhancement

#124 [DOC] GitHub API 활용 방법에 대한 자료 요청 에 대한 PR
  docs/github-api-guide.md
  docs/project_guidelines.md
Labels: documentation

#122 [FEAT] 기여도 비율 추가
  lib/analyzer.js
Labels: enhancement

#144 README.md 내 cache 관련 설명 한글화
  README.md
  Readme_Template.md
Labels: documentation

#149 [REFACTOR] .env 파일 업데이트 로직 단순화 개선 요청 에 대한 PR
  index.js
Labels: enhancement

#160 [DOC] .gitignore에 .DS_Store 추가
  .gitignore
Labels: enhancement

#166 [FEAT] 참가자 초기화 로직 중복 제거에 대한 PR
  lib/analyzer.js
Labels: enhancement

#178 [FEAT] 로그 메시지 타임스탬프 추가
  index.js
  lib/Utill.js
  lib/analyzer.js
Labels: enhancement

#169 [DOC] Readme_Template.md,token_guide/README.md html태그로 되어 있는 부분 markdown문법에 맞춰 재작성 필요에 대한 PR
  Readme_Template.md
  token_guide/README.md
Labels: documentation

#187 Util.js 함수 분리 내용 README에 추가
  README.md
  Readme_Template.md
Labels: documentation

#191 [FEAT] error.status가 없는 경우 오류 메시지가 누락되어 원인 파악이 어려움에 대한 PR
  lib/analyzer.js
Labels: enhancement

#198 [BUG] 테이블 깨짐 개선 요청
  lib/analyzer.js
Labels: enhancement

#199 [BUG] 생성되는 차트의 값 오류 수정
  lib/analyzer.js
Labels: bug

#212 Fix perm for index.js
  index.js
Labels: bug

#210 Github Personal Access Token 발급 가이드 문서 디렉토리 이동
  README.md
  Readme_Template.md
  docs/img/1.jpg
  docs/img/2.jpg
  docs/img/3.jpg
  docs/img/4.jpg
  docs/img/5.jpg
  docs/img/6.jpg
  docs/token_guide.md
Labels: documentation

#226 4글자 이상의 한글 이름과, 영문 이름이 제대로 마스킹 처리되지 않음 수정
  lib/analyzer.js
Labels: bug

#229 [STYLE] 오타 수정
  README.md
Labels: typo

#232 오타수정 - 잘못된 코드 블록 표기 ('''bash → ```bash) 수정
  README.md
  Readme_Template.md
Labels: typo

#241 [FEAT]단순 오타 수정 PR과 내용 추가/재구성 PR 의 구분 구현
  lib/analyzer.js
Labels: enhancement

#267 [DOC] README.md안에 있는 내용 정리에 대한 PR
  README.md
  Readme_Template.md
  docs/esm_guide.md
Labels: documentation

#263 [FEAT] 차트 가독형 향상을 위한 흰색 배경 기능 추가 (#260)
  lib/analyzer.js
Labels: enhancement

#269 [REFACT] index.js 내 -r 옵션 검사를 중복으로 하고 있습니다. 에 대한 PR
  index.js
Labels: enhancement

#289 Update index.js[REFACT] index.js에서 Util.js로 넘어간 함수들의 제거 요청에 대한 PR
  index.js
Labels: enhancement

#290 text 포맷이 CSV가 아닌 사람이 보기좋게 정렬된 형태의 txt 파일로 생성에 대한 PR입니다.
  README.md
  index.js
  lib/GenerateReadme.js
  lib/analyzer.js
Labels: enhancement

#302 [DOC] 로그 레벨별 사용 가이드라인을 README에 문서화
  README.md
  Readme_Template.md
Labels: documentation
